Repository hereisSwapnil/ExamTime, pull requests merged in 2024-05, with the labels that each got.

#34 feat: Added coins attribute and leaderboard feature
  client/src/App.jsx
  client/src/components/DocGrid/DocGrid.jsx
  client/src/components/LeaderBoardTable/LeaderBoardTable.jsx
  client/src/components/Leaderboard/LeaderBoard.jsx
  client/src/components/Navbar/Navbar.jsx
  server/controllers/note.controller.js
  server/controllers/user.controller.js
  server/models/user.model.js
  server/routes/user.routes.js
Labels: level3, gssoc

#24 Fix Issue No #20: The title of the website
  client/index.html
Labels: under review

#39 fix : notescard height
  client/src/components/DocGrid/DocGrid.jsx
Labels: level2, gssoc

#71 fix: nodemon and added .gitignore
  .gitignore
  package-lock.json
  package.json
Labels: level1, gssoc

#67 fead:added bookmark notes feature
  client/src/Context/UserContext.jsx
  client/src/components/DocGrid/DocGrid.jsx
  server/controllers/note.controller.js
  server/models/user.model.js
  server/routes/note.routes.js
Labels: level2, gssoc

#65 feat: View all notification page
  client/src/App.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/NotifcationPage/Notifcation.jsx
Labels: level3, gssoc

#82 Title and fav updated
  client/index.html
  client/src/assets/favIcon.jpg
Labels: level2, gssoc

#70 -Login/Logout
  README.md
  client/src/components/Login/Login.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Signup/Signup.jsx
  server/controllers/user.controller.js
  server/routes/user.routes.js
Labels: level2, gssoc

#83 feat: automate greeting using github action
  .github/workflows/greetings.yml
Labels: level2, gssoc

#80 feat: Dynamic searching without page reloading Issue 16
  client/src/components/DocGrid/DocGrid.jsx
Labels: level2, gssoc

#56 removed extra curly braces in likeNote function
  client/src/components/DocGrid/DocGrid.jsx
  client/src/components/LikeButton/LikeButton.jsx
Labels: level1, gssoc

#108 feature:pagination on the leaderboard
  client/src/components/LeaderBoardTable/LeaderBoardTable.jsx
Labels: level1, gssoc

#111 Added Responsive Footer and change Nodemon into dev-dependency
  client/.env.dev
  client/.env.sample
  client/src/App.jsx
  client/src/components/Footer/index.jsx
  server/.env.dev
  server/.env.sample
  server/package-lock.json
  server/package.json
Labels: level1, gssoc

#115 Added validation using react-toastify on both login as well as registration page
  client/src/components/Login/Login.jsx
  client/src/components/Signup/Signup.jsx
Labels: level2, gssoc

#109 Containerization
  client/Dockerfile
  docker-compose.yml
  server/Dockerfile
Labels: level2, gssoc

#128 make 2 apis for format the dashboard (getting specific note)
  server/controllers/note.controller.js
  server/models/note.model.js
  server/routes/note.routes.js
Labels: level2, gssoc

#88 "Added UserContext and Loader components to Signup page"
  client/src/components/Signup/Signup.jsx
Labels: level1, gssoc

#99 Fixing Document Accessibility for Uploaded PDF
  client/src/components/UploadPage/UploadPage.jsx
  server/db/index.js
  server/package.json
Labels: level2, gssoc

#124 Settings Page Added
  client/src/App.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Settings/Setting.jsx
Labels: level3, gssoc

#141 fix: removed console log on leaderboard
  client/src/components/LeaderBoardTable/LeaderBoardTable.jsx
Labels: level1, gssoc

#114 Fix: the Fluctuating issue of Signup Form in Username Field.
  client/src/components/Signup/Signup.jsx
Labels: level1, gssoc

#132 change route path from # to actual path
  client/package-lock.json
  client/src/components/Footer/index.jsx
  server/package-lock.json
Labels: level1, gssoc

#156 BUGFIX-#130: Navigation Errors
  client/src/components/Navbar/Navbar.jsx
Labels: level2, gssoc

#161 in footer year should be come dynamically #159
  client/src/components/Footer/index.jsx
Labels: level1, gssoc

#163 Implement Feature: Remove the request when someone uploads notes for it
  client/src/App.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/NotifcationPage/Notifcation.jsx
  client/src/components/UploadPage/UploadPage.jsx
  server/controllers/request.controller.js
  server/routes/request.routes.js
Labels: under review

#166 cursor pointer ui/ux fixed
  client/package-lock.json
  client/src/components/DocGrid/DocGrid.jsx
Labels: level1, gssoc

#168 fixed : Bring the eye icons in the confirm password field #143
  client/src/components/Signup/Signup.jsx
Labels: level1, gssoc

#189 CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: level1, gssoc

#185 Update README.md to support new contributors
  README.md
Labels: level1, gssoc

#171 Fix Formatting and Content Issues in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc

#165 Create requirements.txt
  requirements.txt
Labels: level1, gssoc

#107 Updated Readme
  README.md
Labels: level1, gssoc

#152 fix:fixed the next and the last button on the last tab of the leaderbord
  client/package-lock.json
  client/src/components/LeaderBoardTable/LeaderBoardTable.jsx
Labels: under review

#200 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc

#211 FIX: Restructure the Routes to Show navbar after login and increase the code reusability
  client/package-lock.json
  client/src/App.jsx
  client/src/MasterPage.jsx
  client/src/components/Dashboard/Dashboard.jsx
  client/src/components/Leaderboard/LeaderBoard.jsx
  client/src/components/NotifcationPage/Notifcation.jsx
  client/src/components/RequestPage/RequestPage.jsx
  client/src/components/UploadPage/UploadPage.jsx
  server/package-lock.json
Labels: level2, gssoc

#228 Notes thumnail
  client/package-lock.json
  client/package.json
  client/src/components/UploadPage/UploadPage.jsx
Labels: level2, gssoc

#242 Added Hindi Lang
  client/package-lock.json
  client/package.json
  client/src/components/DocGrid/DocGrid.jsx
  client/src/components/Footer/index.jsx
  client/src/components/LeaderBoardTable/LeaderBoardTable.jsx
  client/src/components/NotifcationPage/Notifcation.jsx
  client/src/components/RequestPage/RequestPage.jsx
  client/src/components/Settings/Setting.jsx
  client/src/components/UploadPage/UploadPage.jsx
  client/src/main.jsx
  client/src/utils/appStore.js
  client/src/utils/configSlice.js
  client/src/utils/constants.js
  client/src/utils/langaugeConstant.js
Labels: level2, gssoc

#248 fixed input selection not visibile issue
  client/src/index.css
Labels: level1, gssoc

#254 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-pr-merge.yml
Labels: level1, gssoc

#240 FIX: Website does not loading and fix reload on links in footer
  client/src/components/Footer/index.jsx
  client/src/components/Navbar/Navbar.jsx
Labels: level1, gssoc
